//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ignite.Framework.Micro.Common.Services
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Ignite.Framework.Micro.Common.Services.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            StoppingHosts = -31843,
            ClearingHosts = -31745,
            StartingHosts = -30509,
            TimeoutEventOccurred = -20989,
            ExceptionOccurred = -19817,
            AddedNewHost = -16348,
            StartingService = -11632,
            AttemptingToStartService = 8220,
            ServiceHasStopped = 9290,
            AttemptingToStopService = 10704,
            ErrorAttemptingToStopService = 14930,
            CancellationRequest = 15983,
            AllHostsRemoved = 22908,
            DisposeError = 24388,
            ErrorOccuredWhileTransferringData = 27052,
        }
    }
}
